import Card from "react-bootstrap/Card";
const Pelicula = () => {
    return (
        <>
            <article className="col-12 col-md-4 mt-3 bg-ligth ">
                <Card>
                    <Card.Body>
                        <Card.Title className="lead">
                            <i className="bi bi-film"></i> Titulo
                        </Card.Title>
                        <Card.Subtitle className="mb-2 text-muted">Categoria</Card.Subtitle>
                        <Card.Text>Descripción quick example text to build on the card title and make up the bulk of the card's content.</Card.Text>
                    </Card.Body>
                </Card>
            </article>
            <article className="col-12 col-md-4 mt-3 bg-ligth ">
                <Card>
                    <Card.Body>
                        <Card.Title className="lead">
                            <i className="bi bi-film"></i> Titulo
                        </Card.Title>
                        <Card.Subtitle className="mb-2 text-muted">Categoria</Card.Subtitle>
                        <Card.Text>Descripción quick example text to build on the card title and make up the bulk of the card's content.</Card.Text>
                    </Card.Body>
                </Card>
            </article>
            <article className="col-12 col-md-4 mt-3 bg-ligth ">
                <Card>
                    <Card.Body>
                        <Card.Title className="lead">
                            <i className="bi bi-film"></i> Titulo
                        </Card.Title>
                        <Card.Subtitle className="mb-2 text-muted">Categoria</Card.Subtitle>
                        <Card.Text>Descripción quick example text to build on the card title and make up the bulk of the card's content.</Card.Text>
                    </Card.Body>
                </Card>
            </article>
            <article className="col-12 col-md-4 mt-3 bg-ligth ">
                <Card>
                    <Card.Body>
                        <Card.Title className="lead">
                            <i className="bi bi-film"></i> Titulo
                        </Card.Title>
                        <Card.Subtitle className="mb-2 text-muted">Categoria</Card.Subtitle>
                        <Card.Text>Descripción quick example text to build on the card title and make up the bulk of the card's content.</Card.Text>
                    </Card.Body>
                </Card>
            </article>
            <article className="col-12 col-md-4 mt-3 bg-ligth ">
                <Card>
                    <Card.Body>
                        <Card.Title className="lead">
                            <i className="bi bi-film"></i> Titulo
                        </Card.Title>
                        <Card.Subtitle className="mb-2 text-muted">Categoria</Card.Subtitle>
                        <Card.Text>Descripción quick example text to build on the card title and make up the bulk of the card's content.</Card.Text>
                    </Card.Body>
                </Card>
            </article>
            <article className="col-12 col-md-4 mt-3 bg-ligth ">
                <Card>
                    <Card.Body>
                        <Card.Title className="lead">
                            <i className="bi bi-film"></i> Titulo
                        </Card.Title>
                        <Card.Subtitle className="mb-2 text-muted">Categoria</Card.Subtitle>
                        <Card.Text>Descripción quick example text to build on the card title and make up the bulk of the card's content.</Card.Text>
                    </Card.Body>
                </Card>
            </article>
        </>
    );
};

export default Pelicula;
